resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "{{kubernetes-version}}"
- name: concourse-http-resource
  type: docker-image
  source:
    repository: edtan1/concourse-http-resource

resources:
- name: kubernetes-cluster
  type: kubernetes
  icon: kubernetes
  source:
    insecure_skip_tls_verify: {{kubernetes-skip-tls-verification}}
    kubeconfig: {{kubernetes-config}}
    context: {{kubernetes-context}}
    namespace: {{kubernetes-namespace}}
- name: container-image
  type: docker-image
  icon: docker
  source:
    repository: ((container-image))
- name: drupal-http-endpoint
  type: concourse-http-resource
  source:
    url: {{drupal-update-endpoint}}
    method: "GET"

jobs:
- name: deploy-latest-container-image
  plan:
  - get: container-image
    trigger: true
    params:
      skip_download: true
  - put: kubernetes-cluster
    params:
      kubectl: |
        set image deployment ((kubernetes-deployment)) ((kubernetes-container))=$(cat container-image/repository)@$(cat container-image/digest)
      wait_until_ready: {{kubernetes-wait-until-ready}}
- name: update-drupal
  plan:
  - get: kubernetes-cluster
    passed: [deploy-latest-container-image]
    trigger: true
  - put: drupal-http-endpoint
