apiVersion: v1
kind: Namespace
metadata:
  name: kpack-builders
---
apiVersion: build.pivotal.io/v1alpha1
kind: ClusterBuilder
metadata:
  namespace: kpack-builders
  name: default
spec:
  image: cloudfoundry/cnb:full
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: kpack-builders
  annotations:
    build.pivotal.io/docker: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: USER
  password: PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: kpack-builders
  annotations:
    build.pivotal.io/git: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: USER
  password: PASSWORD
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-service-account
  namespace: kpack-builders
secrets:
  - name: dockerhub-creds
  - name: github-creds